### PR TITLE
Cached current position

### PR DESCRIPTION
**Pull request by comaid**
Hi, Benjamin.

I implemented a cache function in CurrentPos.

CurrentPos seems to require O(n) complexity each time, and is slow because it calls delegate every character.

I'm sorry,but please delete unnecessary comments and codes if you merge this code.
Also, change the variable names if you want.

I wrote my parser, but it was slow. then I wrote a profiling tool for pidgin.
Finally,I found the reason why my parser is slow. CurrentPos was the cause

### CODE REVIEW

**Comment by comaid** [comment]
I seem to have failed. I'll try to fix it.

**Comment by comaid** [comment]
I read the code carefully and noticed it to eliminate my bug.
CurrentPos is slow when parse a string after a file read,because _span is so large.
When parse a stream, CurrentPos is fast enough, because _span is small.

So, I cancel the pull request. Sorry.

**Comment by benjamin-hodgson** [comment]
Sounds like there could nonetheless be some room for improvement when passing from a long span without backtracking

**Comment by benjamin-hodgson** [comment]
Addressed in 43973fee51535d339d0f0edcf2723bb82cd151ff

**Pull request closed without merging**
